export { VectorDB } from './vector-db.js';
export {
    DatabaseClosedError,
    IndexBuildConflictError,
    IndexNotReadyError,
    OperationCancelledError,
    RecordConflictError,
    RecordNotFoundError,
    SchemaMismatchError,
    UnsupportedEnvironmentError,
    ValidationError,
    VecalError,
} from './errors.js';
export type {
    ComparisonValue,
    EnsureIndexOptions,
    HNSWConfig,
    IndexBuildProgress,
    IndexState,
    IndexStatus,
    JSONPrimitive,
    JSONValue,
    Metadata,
    Metric,
    SearchOptions,
    SearchResult,
    SearchStrategy,
    VectorDBOpenOptions,
    VectorInput,
    VectorRecord,
    VectorUpdate,
    Where,
    WhereOperator,
    WorkerLike,
} from './types.js';
